name: Deploy web client bundles
description: Download the built remote bundle artifact and sync it into the live bundle directory

inputs:
  bundle_file_dir:
    description: The file directory where the bundles should go to
    required: true
  bundle_artifact_name:
    description: The name of bundle artifact file
    required: true

runs:
  using: composite
  steps:
    - name: Download remote bundle artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.bundle_artifact_name }}
        path: ${{ runner.temp }}/bundle-download

    - name: Sync remote bundles
      shell: bash
      env:
        TMP_DIR: ${{ runner.temp }}/bundle-download
        BUNDLE_FILE_DIR: ${{ inputs.bundle_file_dir }}
      run: |
        shopt -s nullglob

        mkdir -p "${BUNDLE_FILE_DIR}"

        for bundle_dir in "${TMP_DIR}"/*/; do
          bundle_name="$(basename "${bundle_dir}")"
          dest_dir="${BUNDLE_FILE_DIR}/${bundle_name}"
          mkdir -p "${dest_dir}"

          rsync -a "${bundle_dir}" "${dest_dir}/"
        done

    - name: Sync remote bundle catalog
      shell: bash
      env:
        TMP_DIR: ${{ runner.temp }}/bundle-download
        BUNDLE_FILE_DIR: ${{ inputs.bundle_file_dir }}
      run: |
        rsync -a "${TMP_DIR}/catalog.json" "${BUNDLE_FILE_DIR}/catalog.json"
